# Generated by Django 5.1.5 on 2025-02-17 10:01

import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Sarlavha')),
                ('main_description', models.TextField(verbose_name="asosiy page uchun ma'lumot")),
                ('description', models.TextField(verbose_name="Biz haqimizda page uchun ma'lumot")),
                ('small_image', models.FileField(upload_to='', verbose_name='asosiy page uchun rasm')),
                ('large_image', models.FileField(upload_to='', verbose_name='Biz haqimizda page uchun rasm')),
            ],
            options={
                'verbose_name': 'BizHaqimizda',
                'verbose_name_plural': 'BizHaqimizda',
                'db_table': 'BizHaqimizda',
            },
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='icon/%Y/%m', verbose_name='vebsite iconkasi')),
                ('logo', models.FileField(upload_to='logo/%Y/%m', verbose_name='Logotip bu navbardagisi')),
                ('logo_footer', models.FileField(upload_to='logo/%Y/%m', verbose_name='Logotip bu footerdagisi')),
                ('company_name', models.TextField(verbose_name="Kompaniya to'liq nomi")),
                ('location', models.TextField(verbose_name='Manzil')),
                ('telegram', models.CharField(max_length=256, verbose_name='telegram url')),
                ('instagram', models.CharField(max_length=256, verbose_name='instagram url')),
                ('facebook', models.CharField(max_length=256, verbose_name='facebook url')),
                ('youtube', models.CharField(max_length=256, verbose_name='youtube url')),
                ('linkedin', models.CharField(max_length=256, verbose_name='linkedin url')),
            ],
            options={
                'verbose_name': 'Asosiy',
                'verbose_name_plural': 'Asosiy kompanentlar',
                'db_table': 'Asosiy',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Mahsulot nomi')),
                ('about', models.CharField(max_length=256, verbose_name='Mahsulot haqida')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='url-name')),
                ('side', models.CharField(choices=[("o'ng", "o'ng"), ('chap', 'chap')], max_length=256, verbose_name='qaysi tomonda tursin')),
                ('description', models.TextField(verbose_name='description')),
                ('main_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='asosiy rasm')),
                ('is_top', models.BooleanField(default=False, verbose_name='Asosiy pageda tursinmi')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('content', models.TextField(verbose_name="qo'llanishi va qo'shimcha ma'lumotlar")),
            ],
            options={
                'verbose_name': 'Yangiliklar',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Mahsulot nomi')),
                ('about', models.CharField(max_length=256, verbose_name='Mahsulot haqida')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='url-name')),
                ('description', models.TextField(verbose_name='description')),
                ('main_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='asosiy rasm')),
                ('is_top', models.BooleanField(default=False, verbose_name='Asosiy pageda tursinmi')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('content', models.TextField(verbose_name="qo'llanishi va qo'shimcha ma'lumotlar")),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'db_table': 'Mahsulot',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='icon/%Y/%m', verbose_name='header slider')),
                ('title', models.CharField(max_length=256, verbose_name='Sarlavha')),
                ('about', models.TextField(verbose_name='Haqida')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Header Slider',
                'db_table': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='newss/%Y/%m/', verbose_name="yangi mahsulot uchun qo'shimcha rasmlar")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='common.news')),
            ],
            options={
                'verbose_name': 'Yangi mahsulot rasmlari',
                'verbose_name_plural': 'Yangi mahsulot rasmlari',
                'db_table': 'Yangi mahsulot rasmlari',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='products/%Y/%m/', verbose_name="mahsulot uchun qo'shimcha rasmlar")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='common.products')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmlar',
                'verbose_name_plural': 'Mahsulotlar rasmlar',
                'db_table': 'Mahsulot rasmlar',
            },
        ),
    ]
