# Generated by Django 5.1.2 on 2025-02-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='icon/%Y/%m', verbose_name='vebsite iconkasi')),
                ('logo', models.FileField(upload_to='logo/%Y/%m', verbose_name='Logotip bu navbardagisi')),
                ('logo_footer', models.FileField(upload_to='logo/%Y/%m', verbose_name='Logotip bu footerdagisi')),
                ('company_name', models.TextField(verbose_name="Kompaniya to'liq nomi")),
                ('location', models.TextField(verbose_name='Manzil')),
                ('telegram', models.CharField(max_length=256, verbose_name='telegram url')),
                ('instagram', models.CharField(max_length=256, verbose_name='instagram url')),
                ('facebook', models.CharField(max_length=256, verbose_name='facebook url')),
                ('youtube', models.CharField(max_length=256, verbose_name='youtube url')),
                ('linkedin', models.CharField(max_length=256, verbose_name='linkedin url')),
            ],
            options={
                'verbose_name': 'Asosiy',
                'verbose_name_plural': 'Asosiy kompanentlar',
                'db_table': 'Asosiy',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='icon/%Y/%m', verbose_name='header slider')),
                ('title', models.CharField(max_length=256, verbose_name='Sarlavha')),
                ('about', models.TextField(verbose_name='Haqida')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Header Slider',
                'db_table': 'Slider',
            },
        ),
    ]
