# Generated by Django 5.1.5 on 2025-02-02 07:17

import ckeditor.fields
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Mahsulot nomi')),
                ('about', models.CharField(max_length=256, verbose_name='Mahsulot haqida')),
                ('slug', models.SlugField(max_length=256, verbose_name='slug-name')),
                ('description', models.TextField(verbose_name='description')),
                ('main_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='asosiy rasm')),
                ('image_1', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='rasm - 1')),
                ('image_2', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='rasm - 2')),
                ('image_3', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='rasm - 3')),
                ('image_4', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='rasm - 4')),
                ('image_5', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='rasm - 5')),
                ('is_top', models.BooleanField(default=False, verbose_name='project is top')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('content', ckeditor.fields.RichTextField(verbose_name="qo'llanishi va qo'shimcha ma'lumotlar")),
            ],
        ),
    ]
