# Generated by Django 5.1.5 on 2025-02-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelTable(
            name='products',
            table='Mahsulot',
        ),
    ]
