# Generated by Django 5.1.5 on 2025-02-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_products_options_alter_products_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='content',
            field=models.TextField(verbose_name="qo'llanishi va qo'shimcha ma'lumotlar"),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='url-name'),
        ),
    ]
