# Generated by Django 5.1.2 on 2025-02-03 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_products_content_alter_products_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Sarlavha')),
                ('main_description', models.TextField(verbose_name="asosiy page uchun ma'lumot")),
                ('description', models.TextField(verbose_name="Biz haqimizda page uchun ma'lumot")),
                ('small_image', models.FileField(upload_to='', verbose_name='asosiy page uchun rasm')),
                ('large_image', models.FileField(upload_to='', verbose_name='Biz haqimizda page uchun rasm')),
            ],
            options={
                'verbose_name': 'BizHaqimizda',
                'verbose_name_plural': 'BizHaqimizda',
                'db_table': 'BizHaqimizda',
            },
        ),
    ]
