# Generated by Django 5.1.2 on 2025-02-03 05:28

import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Yangilik nomi')),
                ('title', models.TextField(verbose_name='Sarlavha')),
                ('about', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('usage', models.TextField(verbose_name="Qo'llanishi va boshqa ma'lumotlar")),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='url-name')),
                ('is_top', models.BooleanField(default=False, verbose_name='Asosiy pageda tursinmi')),
                ('left_side', models.CharField(choices=[("o'ng", "o'ng"), ('chap', 'chap')], max_length=256, verbose_name="o'ngda tursinmi")),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('main_image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='asosiy rasm')),
                ('image_1', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='rasm - 1')),
                ('image_2', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='rasm - 2')),
                ('image_3', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='rasm - 3')),
                ('image_4', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='rasm - 4')),
                ('image_5', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=95, scale=0.5, size=[1920, 1080], upload_to='products/%Y/%m', verbose_name='rasm - 5')),
            ],
            options={
                'verbose_name': 'Yangiliklar',
                'verbose_name_plural': 'Yangiliklar',
                'db_table': 'Yangiliklar',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Asosiy pageda tursinmi'),
        ),
    ]
