# Generated by Django 5.1.2 on 2025-02-03 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_news_alter_products_is_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='left_side',
        ),
        migrations.AddField(
            model_name='news',
            name='side',
            field=models.CharField(choices=[("o'ng", "o'ng"), ('chap', 'chap')], default=datetime.datetime(2025, 2, 3, 10, 30, 59, 994332, tzinfo=datetime.timezone.utc), max_length=256, verbose_name='qaysi tomonda tursin'),
            preserve_default=False,
        ),
    ]
